# Generated by Django 6.0.3 on 2026-03-11 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_images_good_description_alter_good_brand_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='images',
        ),
        migrations.AddField(
            model_name='carmodel',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='images/'),
        ),
    ]
