# Generated by Django 6.0.3 on 2026-03-11 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_remove_carmodel_images_carmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='images/'),
        ),
    ]
