# Generated by Django 6.0.3 on 2026-03-12 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_alter_carmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='images/default.jpg', upload_to='images/category_imgs/'),
        ),
    ]
