# Generated by Django 6.0.3 on 2026-03-12 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='brand',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='landing.brand'),
        ),
    ]
