# Generated by Django 6.0.3 on 2026-03-12 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0008_alter_good_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='good',
            old_name='model',
            new_name='title',
        ),
    ]
