# Generated by Django 6.0.3 on 2026-03-12 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0009_rename_model_good_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='car_model',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='landing.carmodel'),
        ),
    ]
