# Generated by Django 6.0.3 on 2026-03-12 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0010_good_car_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='images',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='landing.images'),
        ),
    ]
