# Generated by Django 6.0.3 on 2026-03-12 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0011_good_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good',
            name='images',
        ),
        migrations.AddField(
            model_name='images',
            name='good',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='good', to='landing.good'),
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(default='images/default.jpg', upload_to='images/goods/'),
        ),
    ]
